name: ci
on:
  push:
    tags:
      - 'v*'
    branches:
      - 'create-pull-request/**'
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    name: ci
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get shortsha
        id: vars
        run: |
          echo ::set-output name=sha_short::sha-$(git rev-parse --short=7 ${{ github.sha }})
          echo ::set-output name=structurizr_version::$(cat structurizr-cli-latest.txt | sed 's/[^0-9.]*//g')

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.7.0

      - name: Cache Docker layers
        uses: actions/cache@v3.0.1
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v3.7.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=tag

      - name: Build
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          file: ./Dockerfile
          load: true
          cache-to: type=local,dest=/tmp/.buildx-cache
          cache-from: type=local,src=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            org.opencontainers.image.description=structurizr-cli docker container
            org.opencontainers.image.authors=Maksim Milykh aidmax@mail.ru
          build-args: |
            STRUCTURIZR_VERSION=${{ steps.vars.outputs.structurizr_version }}

      - name: Setting permissions and tags
        run: |
          chmod +x ./runstr.sh
          sed -i 's/docker:latest/docker:${{ steps.vars.outputs.sha_short }}/g' ./runstr.sh

     #TODO: Add tests for other commands

      - name: Checking "push" command
        # See https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
        if: github.actor!= 'dependabot[bot]'
        run: |
          ./runstr.sh push \
             -id ${{ secrets.STZR_ID }} \
             -key ${{ secrets.STZR_API_KEY }} \
             -secret ${{ secrets.STZR_API_SECRET }} \
             -workspace ./tests/workspace.dsl

      - name: Checking "pull" command
        # See https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
        if: github.actor!= 'dependabot[bot]'
        run: |
          ./runstr.sh pull \
             -id ${{ secrets.STZR_ID }} \
             -key ${{ secrets.STZR_API_KEY }} \
             -secret ${{ secrets.STZR_API_SECRET }}

      - name: Checking "pull" command verify downloaded workspace files
        # See https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
        if: github.actor!= 'dependabot[bot]'
        run: |
          files=$(ls ${{ github.workspace }}/*.json 2> /dev/null | wc -l)
          if [[ "$files" != 0 ]]
          then
            echo OK
          else
            exit 1
          fi

      - name: Checking "validate" command
        # See https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
        if: github.actor!= 'dependabot[bot]'
        run: |
          ./runstr.sh validate \
             -workspace ./tests/workspace.dsl

      - name: Checking "list" command
        # See https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
        if: github.actor!= 'dependabot[bot]'
        run: |
          ./runstr.sh list \
             -workspace ./tests/workspace.dsl

      - name: Checking "export" command
        # See https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/
        if: github.actor!= 'dependabot[bot]'
        run: |
          for format in plantuml mermaid websequencediagrams dot ilograph json dsl theme
            do
              ./runstr.sh export -workspace ./tests/workspace.dsl -format $format;
            done

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}'
          format: 'table'
          #FIXME: https://github.com/aquasecurity/trivy-action/issues/91
          # exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2.10.0
        if: github.event_name != 'pull_request'
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            org.opencontainers.image.description=structurizr-cli docker container
            org.opencontainers.image.authors=Maksim Milykh
          build-args: |
            STRUCTURIZR_VERSION=${{ steps.vars.outputs.structurizr_version }}

      # Disable this due to https://github.com/actions/delete-package-versions/issues/28
      # - name: Delete oldest image
      #   if: github.event_name != 'pull_request'
      #   uses: actions/delete-package-versions@v1
      #   with:
      #     package-name: 'structurizr-cli-docker'
