name: ci
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    name: ci
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get shortsha
        id: vars
        run: |
          echo ::set-output name=sha_short::sha-$(git rev-parse --short=7 ${{ github.sha }})
          echo ::set-output name=structurizr_version::$(cat structurizr-cli-latest.txt | sed 's/[^0-9.]*//g')

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2.2.0
        with:
          images: ghcr.io/${{ github.repository }}
          tag-sha: true

      - name: Build
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: ./Dockerfile
          load: true
          cache-to: type=local,dest=/tmp/.buildx-cache
          cache-from: type=local,src=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            org.opencontainers.image.description=structurizr-cli docker container
            org.opencontainers.image.authors=Maksim Milykh aidmax@mail.ru
          build-args: |
            STRUCTURIZR_VERSION=${{ steps.vars.outputs.structurizr_version }}

      - name: CVE scan image
        uses: docker://docker.io/aquasec/trivy:latest
        with:
          args: >-
            --cache-dir /var/lib/trivy
            --no-progress
            --exit-code 1
            --severity MEDIUM,HIGH,CRITICAL
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}

      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2.2.2
        if: github.event_name != 'pull_request'
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: |
            ${{ steps.docker_meta.outputs.labels }}
            org.opencontainers.image.description=structurizr-cli docker container
            org.opencontainers.image.authors=Maksim Milykh
          build-args: |
            STRUCTURIZR_VERSION=${{ steps.vars.outputs.structurizr_version }}

      # Disable this due to https://github.com/actions/delete-package-versions/issues/28
      # - name: Delete oldest image
      #   if: github.event_name != 'pull_request'
      #   uses: actions/delete-package-versions@v1
      #   with:
      #     package-name: 'structurizr-cli-docker'
