name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build an image
        id: setenv
        run: |
          IMAGE=aidmax/structurizr-cli-docker:${GITHUB_SHA}
          echo "::set-output name=image::$IMAGE"

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{ steps.setenv.outputs.image }}

      - name: CVE scan image
        uses: docker://docker.io/aquasec/trivy:latest
        with:
          args: --cache-dir /var/lib/trivy --no-progress --exit-code 1 --severity MEDIUM,HIGH,CRITICAL ${{ steps.setenv.outputs.image }}
